name: Weather App Build and Deploy

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push: # Triggers the workflow on push events
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'njweatherforecast' # Replace with your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: './GithubActions/publish' # Path to the build output directory
  DOTNET_VERSION: '9.x' # Specify the .NET version to use
  SOLUTION_PATH: 'GithubActions.sln' # Path to the solution file
  API_PROJECT_PATH: 'GithubActions/GithubActions.csproj' # Path to the API project file
  PUBLISH_DIR: "./publish"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4 
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Ensure this secret is set in your repository
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}